CREATE TABLE IF NOT EXISTS PeriodosEscala (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  data_inicio DATE NOT NULL,
  data_fim DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DisponibilidadesPeriodo (
  id INT AUTO_INCREMENT PRIMARY KEY,
  periodo_id INT NOT NULL,
  coroinha_id INT NOT NULL,
  disponibilidade_dias JSON NOT NULL,
  disponibilidade_locais JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (periodo_id) REFERENCES PeriodosEscala(id) ON DELETE CASCADE,
  FOREIGN KEY (coroinha_id) REFERENCES Coroinhas(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ServicosRealizados (
  id INT AUTO_INCREMENT PRIMARY KEY,
  periodo_id INT NOT NULL,
  coroinha_id INT NOT NULL,
  data DATE NOT NULL,
  horario TIME NOT NULL,
  local VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (periodo_id) REFERENCES PeriodosEscala(id) ON DELETE CASCADE,
  FOREIGN KEY (coroinha_id) REFERENCES Coroinhas(id) ON DELETE CASCADE
); 